import '@/styles/globals.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import 'primeicons/primeicons.css';
import { ToastProvider } from '@/contexts/ToastContext';
import { UserProvider } from '@/contexts/UserContext';
import { Poppins } from 'next/font/google';
import type { AppProps } from 'next/app';
import Head from 'next/head';

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: '100',
});

export default function MyApp({ Component, pageProps }: AppProps) {
    
    return (
        <>
            <Head>
                <title>Frontend Development Test - PSN</title>
                <meta name="description" content="Generated by NextJS 15.3.0" />
            </Head>
            <div className={`${poppins.variable} cust-outer-container bg-custBackground text-custBlack flex overflow-y-auto overflow-x-hidden drop-shadow-md`}>
                <UserProvider>
                    <ToastProvider>
                        <Component {...pageProps} />
                    </ToastProvider>
                </UserProvider>
            </div>
        </>
    );
}